services:
  bot:
    build: .
    container_name: ira-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DISCORD_APP_TOKEN=${DISCORD_APP_TOKEN}
      - APP_ID=${APP_ID}
      - NEWANIME_URL=${NEWANIME_URL}
    # env_file:         # 이 줄 주석 처리 또는 제거
    #   - .env